[package]
name = "tellmewhy"
version = "0.1.0"
edition = "2021"

[lib]
name = "tellmewhy"
path = "src/lib.rs"

[[bin]]
name = "tellmewhy-bin"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
crossterm = "0.26.1"
unicode-width = "0.1.10"

[dev-dependencies]
pretty_assertions = "1.3.0"
